### ISSUE TITLE
calculate distance between two ring

### ISSUE THREAD

**Issue by rahmanhpu** [MDAnalysis/MDAnalysisTutorial#10]
I am beginner  in python programming and I am using this tutorials as reference to work with MDAnalysis.
I am trying to do similar analysis as given in this article figure 10 (given geometrical criteria ) , 11 and 12 [link]( http://pubs.acs.org/doi/abs/10.1021/jp3080496 ).
In my simulation systems I have total 512 cations, 512 anions. Now I want to calculate distance between two cation ring from centre of geometry (as criteria mention in this articles). For this I have to run a for loop over no of cation and then calculate distance between each cation pairs. I have a problem with selecting range of cation resid because I have also anion in my system. if I am selecting resname CAT this is printing diffrent value than the resid value.

`residue=np.arange(0,1024,2)
resid = traj.atoms.residues[residue]
for i in resid:
C2 = traj.select_atoms("resid i").center_of_geometry()`
It giving error 

  File "/home/rahman/anaconda3/envs/python2/lib/python2.7/site-packages/MDAnalysis/core/Selection.py", line 1030, in _parse_subexp
    raise SelectionError("Selection failed: '{0}'".format(e))

SelectionError: Selection failed: 'Failed to parse number: i'

**Comment by kain88-de** [comment]
Your error is because there isn't a residue with an id (an integer value) in a topology. You have to replace the `i` with the integer like so `'resid {}'.format(i)`. But you short example has other problems as well. You are iterating over a list or residue objects that return a residue object itself that you can use to get the center of mass. See code below.

```python
# generate a list of interesting residue ids
residue_ids = np.arange(0, 1024, 2)
# select residues by python ids, **NOT** PDB or other used Topology ids
residues = traj.atoms.residues[residue_ids]
# create an empty list to store positions of residues
C2_positions = []
# loop over residue objects
for res in residues:
    # append last position
    C2_positions.append(res.center_of_mass())
# convert list to a numpy array with shape (t, 3) for convenience
C2_positions = np.array(C2_positions)
```

We have a [user mailing list](https://groups.google.com/forum/#!forum/mdnalysis-discussion). In the future I recommend you posting there as more people will see your post and can answer.
